sudo: false
language: node_js
node_js:
  - '10'

os:
  - osx
  - linux
  - windows

script:
  - yarn install
  - yarn rebuild
  - yarn run build
  - yarn run dist

deploy:
  provider: script
  script: yarn run dist
  on:
    all_branches: true
  skip_cleanup: true
  file_glob: true
